name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: Redirect
        run: |
          echo '<meta http-equiv="refresh" content="0;url=yohan_boogaert/">' > target/doc/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
