name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Clean
        run: cargo clean

      - name: xtask
        run: cargo xtask

      - uses: docker://pandoc/latex:3.5
        with:
          args: >-
            -f html
            -t pdf
            --pdf-engine=xelatex
            -V geometry:margin=0.5in
            -o target/doc/output.pdf
            target/doc/input.html

      - run: rm target/doc/input.html

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: target/doc/output.pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
