name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: cargo clean
        run: cargo clean

      - name: cargo xtask
        run: cargo xtask

      - run: mkdir output

      - uses: docker://pandoc/latex:3.5
        with:
          args: >-
            -f html
            -t pdf
            --pdf-engine=xelatex
            -V geometry:margin=0.5in
            -o output/result.pdf
            target/doc/yohan_boogaert_1995/input.html

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: output
          path: output
      - run: mv output/result.pdf output/yohan_boogaert_resume.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: output/*
